filters = ["OK", "REJECTED", "WRONG_ANSWER", "RUNTIME_ERROR", "TIME_LIMIT_EXCEEDED",
               "MEMORY_LIMIT_EXCEEDED", "COMPILATION_ERROR", "CHALLENGED", "FAILED",
               "PARTIAL", "PRESENTATION_ERROR", "IDLENESS_LIMIT_EXCEEDED", "SECURITY_VIOLATED",
               "CRASHED", "INPUT_PREPARATION_CRASHED", "SKIPPED", "TESTING", "SUBMITTED"]